version: '3.7'

services:
  db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    depends_on:
      - php
    networks:
      - hr-backend
    container_name: hr-backend-db
  nginx:
    build:
      context: ./..
      dockerfile: docker/nginx/Dockerfile
    restart: always
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - "${VOLUME}:/app"
    depends_on:
      - php
    networks:
      - hr-backend
    container_name: hr-backend-nginx

  php:
    build:
      context: ./..
      dockerfile: "docker/php/Dockerfile-${ENV}"
      args:
        ENV: $ENV
        DB_HOST: $DB_HOST
        DB_NAME: $DB_NAME
        DB_USER: $DB_USER
        DB_PASSWORD: $DB_PASSWORD
    restart: always
    volumes:
      - "${VOLUME}:/app"
    networks:
      - hr-backend
    container_name: hr-backend-php

volumes:
  data-volume:
networks:
  hr-backend:
