#!/usr/bin/env php
<?php
/**
 * Yii Application Initialization Tool
 *
 * In order to run in non-interactive mode:
 *
 * init --env=Development --overwrite=n
 */

if (!extension_loaded('openssl')) {
    die('The OpenSSL PHP extension is required by Yii2.');
}

$params = getParams();
$root = str_replace('\\', '/', __DIR__);
$envs = require "$root/environments/index.php";
$envNames = array_keys($envs);

echo "Yii Application Initialization Tool v1.0\n\n";

$requiredParams = [
    'env' => 'Environment, one of Development and Production',
    'db_host' => 'database host',
    'db_name' => 'database name',
    'db_user' => 'database user',
    'db_password' => 'database password',
];

$envName = null;
if (empty($params['env']) || $params['env'] === '1') {
    echo "Which environment do you want the application to be initialized in?\n\n";
    foreach ($envNames as $i => $name) {
        echo "  [$i] $name\n";
    }
    echo "\n  Your choice [0-" . (count($envs) - 1) . ', or "q" to quit] ';
    $answer = trim(fgets(STDIN));

    if (!ctype_digit($answer) || !in_array($answer, range(0, count($envs) - 1))) {
        echo "\n  Quit initialization.\n";
        exit(0);
    }

    if (isset($envNames[$answer])) {
        $envName = $envNames[$answer];
    }
} else {
    $envName = $params['env'];
}

if (isset($params['no_interactive'])) {
    $isOk = true;

    foreach ($requiredParams as $requiredParamName => $requiredParamDesc) {
        if ((!isset($params[$requiredParamName]) || !$params[$requiredParamName]) && !in_array($requiredParamName, $allowEmpty)) {
            if (isset($params[$requiredParamName]) && $params[$requiredParamName] == 0) continue;
            echo "Required parameter --".$requiredParamName." is missed.\n".$requiredParamDesc."\n\n";
            $isOk = false;
        }
    }

    if (!$isOk) exit(1);
}

if (!in_array($envName, $envNames)) {
    $envsList = implode(', ', $envNames);
    echo "\n  $envName is not a valid environment. Try one of the following: $envsList. \n";
    exit(2);
}

$env = $envs[$envName];

if (empty($params['env'])) {
    echo "\n  Initialize the application under '{$envNames[$answer]}' environment? [yes|no] ";
    $answer = trim(fgets(STDIN));

    if (strncasecmp($answer, 'y', 1)) {
        echo "\n  Quit initialization.\n";
        exit(0);
    }
}

echo "\n  Start initialization ...\n\n";
$all = isset($params['no_interactive']) ? true : false;

$mainDirs = [
    "{$env['path']}",
    "common"
];

foreach ($mainDirs as $dir) {
    $rootPath = "$root/environments/{$dir}";
    if (!is_dir($rootPath)) {
        printError("$rootPath directory does not exist. Check path in $envName environment.");
        exit(3);
    }

    $files = getFileList($rootPath);
    if (isset($env['skipFiles'])) {
        $skipFiles = $env['skipFiles'];
        array_walk($skipFiles, function(&$value) use($env, $root) { $value = "$root/$value"; });
        $files = array_diff($files, array_intersect_key($env['skipFiles'], array_filter($skipFiles, 'file_exists')));
    }

    foreach ($files as $file) {
        if (!copyFile($root, "environments/{$dir}/$file", $file, $all, $params)) {
            break;
        }
    }
}

$callbacks = ['setCookieValidationKey', 'setWritable', 'setExecutable', 'createSymlink', 'removeAllFilesFrom'];
foreach ($callbacks as $callback) {
    if (!empty($env[$callback])) {
        $callback($root, $env[$callback]);
    }
}

$paramsPath = __DIR__ . "/config/params-local.php";
$paramsContent = file_get_contents($paramsPath);

$configPath = __DIR__ . "/config/config-local.php";
$configContent = file_get_contents($configPath);

$dbPath = __DIR__ . "/config/db.php";
$dbContent = file_get_contents($dbPath);

if (isset($params['no_interactive'])) {
    foreach ($requiredParams as $param => $desc) {
        $data = isset($params[$param]) ? $params[$param] : '';

        $template = is_numeric($data) || is_bool($data) ? '/\'<' . $param . '>\'/' : '/<' . $param . '>/';
        if (stripos($paramsContent, $param)) {
            $paramsContent = preg_replace($template, $data, $paramsContent);
        }
        
        if (stripos($configContent,  $param)) {
            $configContent = preg_replace($template, $data, $configContent);
        }
        
        if (stripos($dbContent,  $param)) {
            $dbContent = preg_replace($template, $data, $dbContent);
        }
    }
} else {
    echo "\n Enter database params:";

    echo "\n Enter database host  ";
    $answer = trim(fgets(STDIN));
    $dbContent = preg_replace('/<db_host>/', $answer, $dbContent);

    echo "\n Enter database name  ";
    $answer = trim(fgets(STDIN));
    $dbContent = preg_replace('/<db_name>/', $answer, $dbContent);

    echo "\n Enter database user  ";
    $answer = trim(fgets(STDIN));
    $dbContent = preg_replace('/<db_username>/', $answer, $dbContent);

    echo "\n Enter database password  ";
    $answer = trim(fgets(STDIN));
    $dbContent = preg_replace('/<db_password>/', $answer, $dbContent);
}

file_put_contents($paramsPath, $paramsContent);
file_put_contents($configPath, $configContent);
file_put_contents($dbPath, $dbContent);


echo "\n  ... initialization completed.\n\n";

function getFileList($root, $basePath = '')
{
    $files = [];
    $handle = opendir($root);
    while (($path = readdir($handle)) !== false) {
        if ($path === '.git' || $path === '.svn' || $path === '.' || $path === '..') {
            continue;
        }
        $fullPath = "$root/$path";
        $relativePath = $basePath === '' ? $path : "$basePath/$path";
        if (is_dir($fullPath)) {
            $files = array_merge($files, getFileList($fullPath, $relativePath));
        } else {
            $files[] = $relativePath;
        }
    }
    closedir($handle);
    return $files;
}

function copyFile($root, $source, $target, &$all, $params)
{
    if (!is_file($root . '/' . $source)) {
        echo "       skip $target ($source not exist)\n";
        return true;
    }
    if (is_file($root . '/' . $target)) {
        if (file_get_contents($root . '/' . $source) === file_get_contents($root . '/' . $target)) {
            echo "  unchanged $target\n";
            return true;
        }
        if ($all) {
            echo "  overwrite $target\n";
        } else {
            echo "      exist $target\n";
            echo "            ...overwrite? [Yes|No|All|Quit] ";


            $answer = !empty($params['overwrite']) ? $params['overwrite'] : trim(fgets(STDIN));
            if (!strncasecmp($answer, 'q', 1)) {
                return false;
            } else {
                if (!strncasecmp($answer, 'y', 1)) {
                    echo "  overwrite $target\n";
                } else {
                    if (!strncasecmp($answer, 'a', 1)) {
                        echo "  overwrite $target\n";
                        $all = true;
                    } else {
                        echo "       skip $target\n";
                        return true;
                    }
                }
            }
        }
        file_put_contents($root . '/' . $target, file_get_contents($root . '/' . $source));
        return true;
    }
    echo "   generate $target\n";
    @mkdir(dirname($root . '/' . $target), 0777, true);
    file_put_contents($root . '/' . $target, file_get_contents($root . '/' . $source));
    return true;
}

function getParams()
{
    $rawParams = [];
    if (isset($_SERVER['argv'])) {
        $rawParams = $_SERVER['argv'];
        array_shift($rawParams);
    }

    $params = [];
    foreach ($rawParams as $param) {
        if (preg_match('/^--(\w+)(=(.*))?$/', $param, $matches)) {
            $name = $matches[1];
            $params[$name] = isset($matches[3]) ? $matches[3] : true;
        } else {
            $params[] = $param;
        }
    }
    return $params;
}

function setWritable($root, $paths)
{
    foreach ($paths as $writable) {
        if (is_dir("$root/$writable")) {
            if (@chmod("$root/$writable", 0777)) {
                echo "      chmod 0777 $writable\n";
            } else {
                printError("Operation chmod not permitted for directory $writable.");
            }
        } else {
            printError("Directory $writable does not exist.");
        }
    }
}

function setExecutable($root, $paths)
{
    foreach ($paths as $executable) {
        if (file_exists("$root/$executable")) {
            if (@chmod("$root/$executable", 0755)) {
                echo "      chmod 0755 $executable\n";
            } else {
                printError("Operation chmod not permitted for $executable.");
            }
        } else {
            printError("$executable does not exist.");
        }
    }
}

function removeAllFilesFrom($root, $paths)
{    
    foreach ($paths as $remove) {
        if (file_exists("$root/$remove")) {
            echo "remove all files from $root/$remove/*\n";
            echo exec('rm -rf ' . $root . '/' . $remove . '/*');
        } else {
            printError("$remove does not exist.");
        }
    }
}

function setCookieValidationKey($root, $paths)
{
    foreach ($paths as $file) {
        echo "   generate cookie validation key in $file\n";
        $file = $root . '/' . $file;
        $length = 32;
        $bytes = openssl_random_pseudo_bytes($length);
        $key = strtr(substr(base64_encode($bytes), 0, $length), '+/=', '_-.');
        $content = preg_replace('/(("|\')cookieValidationKey("|\')\s*=>\s*)(""|\'\')/', "\\1'$key'", file_get_contents($file));
        file_put_contents($file, $content);
    }
}

function createSymlink($root, $links)
{
    foreach ($links as $link => $target) {
        //first removing folders to avoid errors if the folder already exists
        @rmdir($root . "/" . $link);
        //next removing existing symlink in order to update the target
        if (is_link($root . "/" . $link)) {
            @unlink($root . "/" . $link);
        }
        if (@symlink($root . "/" . $target, $root . "/" . $link)) {
            echo "      symlink $root/$target $root/$link\n";
        } else {
            printError("Cannot create symlink $root/$target $root/$link.");
        }
    }
}

/**
 * Prints error message.
 * @param string $message message
 */
function printError($message)
{
    echo "\n  " . formatMessage("Error. $message", ['fg-red']) . " \n";
}

/**
 * Returns true if the stream supports colorization. ANSI colors are disabled if not supported by the stream.
 *
 * - windows without ansicon
 * - not tty consoles
 *
 * @return boolean true if the stream supports ANSI colors, otherwise false.
 */
function ansiColorsSupported()
{
    return DIRECTORY_SEPARATOR === '\\'
        ? getenv('ANSICON') !== false || getenv('ConEmuANSI') === 'ON'
        : function_exists('posix_isatty') && @posix_isatty(STDOUT);
}

/**
 * Get ANSI code of style.
 * @param string $name style name
 * @return integer ANSI code of style.
 */
function getStyleCode($name)
{
    $styles = [
        'bold' => 1,
        'fg-black' => 30,
        'fg-red' => 31,
        'fg-green' => 32,
        'fg-yellow' => 33,
        'fg-blue' => 34,
        'fg-magenta' => 35,
        'fg-cyan' => 36,
        'fg-white' => 37,
        'bg-black' => 40,
        'bg-red' => 41,
        'bg-green' => 42,
        'bg-yellow' => 43,
        'bg-blue' => 44,
        'bg-magenta' => 45,
        'bg-cyan' => 46,
        'bg-white' => 47,
    ];
    return $styles[$name];
}

/**
 * Formats message using styles if STDOUT supports it.
 * @param string $message message
 * @param string[] $styles styles
 * @return string formatted message.
 */
function formatMessage($message, $styles)
{
    if (empty($styles) || !ansiColorsSupported()) {
        return $message;
    }

    return sprintf("\x1b[%sm", implode(';', array_map('getStyleCode', $styles))) . $message . "\x1b[0m";
}

function isEmpty($val)
{
    return empty($val) || $val === true;
}
